### ISSUE TITLE
files duplicated when using "/<app-name>/models/ticket" and "<app-name>/models/ticket"

### ISSUE THREAD

**Issue by fivetanley** [joliss/broccoli-es6-concatenator#31]
This happens when you have two similar yet different (one uses a leading `/` one doesn't) in Ember CLI and leads to subtle zalgo when code gets loaded twice:

`import Ticket from "myapp/models/ticket";`

vs 

`import Ticket from "/myapp/models/ticket";`

Two modules with the same code will be defined and loaded separately. This means you have twice as much code loading and also in execution when in the browser.

There should be a hook for normalizing this kind of stuff. I have to pack but I can fill you in later with more details tomorrow. @igorT, @hjdivad, and I ran into this while working on Ember Data.

**Comment by joliss** [comment]
This plugin is deprecated now. I just updated the deprecation notice on the README:

> **This plugin is deprecated and no longer maintained,** as it uses an old version of [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler). It is recommended that you use the [broccoli-es6modules](https://github.com/ember-cli/broccoli-es6modules) plugin instead, which is based on the newer [Esperanto](http://esperantojs.org/) transpiler.

I'm closing all issues and PRs on this repo, since I don't intend on fixing or changing anything with this plugin anymore. If anybody wants me to reopen something, please let me know. :)
